### ISSUE TITLE
Container fails to start after restart

### ISSUE THREAD

**Issue by kolanos** [maryvilledev/alpine-rmq#7]
When starting the container initially it starts without incident, but when the container is restarted I get the following:

```
rabbitmq_1  | mv: can't rename '/srv/rabbitmq_server-3.6.1/etc/rabbitmq/standard.config': No such file or directory
```

**Comment by colebrumley** [comment]
Thanks for the report! The wrapper script wasn't checking to see if `${RABBITMQ_HOME}/etc/rabbitmq/rabbitmq.config` exists before attempting to copy the template there. I added a quick check to see if the file is present before copying, and a quick start+restart test appeared to solve the issue.

**Comment by kolanos** [comment]
@colebrumley Thank you, sir.
