### ISSUE TITLE
Auto-rebuild on the base image upgrade

### ISSUE THREAD

**Issue by frol** [maryvilledev/alpine-rmq#9]
Please, configure your Docker Hub image to auto-rebuild on every Alpine image change.

Also, I have noticed that you use Alpine 3.2; is it possible to migrate to the latest Alpine 3.4?

**Comment by darrellberry** [comment]
hi -- can't successfully build this at the moment, get a

> Error relocating /usr/lib/erlang/erts-8.1/bin/beam.smp: pthread_setname_np: symbol not found

when running 

`rabbitmq-plugins enable --offline rabbitmq_management`

(and indeed if I comment that out and finish the build, get the same error when trying to start the rabbitmq server itself)

Possibly an upstream glibc version problem?

**Comment by frol** [comment]
@darrellberry You may try to base on [`frolvlad/alpine-glibc`](https://github.com/frol/docker-alpine-glibc). Your glibc is outdated.

**Comment by darrellberry** [comment]
ok will try that, thx

**Comment by darrellberry** [comment]
same problem when rebased on  frolvlad/alpine-glibc, sorry. 

easy to replicate -- just clone the master branch and try building

**Comment by marsradiant** [comment]
any fix on this issue?

**Comment by colebrumley** [comment]
The glibc issue with erlang has been reported to the alpine maintainers here https://github.com/gliderlabs/docker-alpine/issues/227

I am preparing to commit the changes necessary for the original request (dynamically rebuilding on base image updates), and to update RMQ to 3.6.5. Not planning to merge until I have a fix for the glibc issue though

**Comment by kitsirota** [comment]
+1 This is a major blocker for us too

**Comment by colebrumley** [comment]
I just merged a bunch of been-meaning-to-do-this-for-too-long changes, including the fix for this. The Dockerfile is using `:latest` explicitly and the Docker Hub repo (which has a new name by the way: `maryville/rabbitmq`) is linked to alpine.

**Comment by frol** [comment]
Thank you!
